### ISSUE TITLE
Unable to trigger an image build

### ISSUE THREAD

**Issue by ecchong** [ahuffman/sat6-create-hosts#7]
What parameters to use to trigger an image build instead of a network build?  From the example, looks like we need to specify build_type but not sure what the value should be.

**Comment by ahuffman** [comment]
Hi @ecchong.  It should be very similar parameters.  The key here is setting up a host group that populates all the necessary values for you ahead of time.  I'd start there, and circle back to this issue when you have set this up.  The main thing you need to do is manage your compute resource images, and add any templates you have there.   Then in the host group you should be able to tie it all together.

Feel free to comment back on this issue, as I'll keep it open to carry on a conversation for others that may be interested.  

Please also provide some details on your compute resource config and imported images.  Also please provide some details on what you have set inside of your host group(s).  That should help with determining what parameters we would need to pass into the role to spin the new VMs up with.

Thanks!

**Comment by ecchong** [comment]
Thanks.  I tried changing the "new_host_virtual.json.j2" template to use 

> "provision_method": "image"

It deployed the VM from template, but not powering it on and it failed when trying to run the finishing template via SSH.  Am I on the right track?  Why "provision_method" is hard coded to build?  
,

**Comment by ahuffman** [comment]
Closed by #8 .  Thanks for your contribution @ecchong !!!!
